ServiceApresVenteApp/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceApresVente.Models;

namespace ServiceApresVenteApp.Controllers
{
    [Authorize(Roles="Responsable")]
    public class ArticlesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;
        private IList<User> _clients;

        public ArticlesController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
            _clients = _userManager.GetUsersInRoleAsync("Client").Result.ToList();
        }

        // GET: Articles
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Articles.Include(a => a.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Articles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // GET: Articles/Create
        public async Task<IActionResult> CreateAsync()
        {
            ViewData["UserId"] = new SelectList(_clients, "Id", "Id");
            return View();
        }

        // POST: Articles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Reference,DateAchat,DureeGarantie,UserId")] Article article)
        {
            if (ModelState.IsValid)
            {
                _context.Add(article);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                // Loop through the errors in the ModelState
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        Debug.WriteLine(error.ErrorMessage); // Print the error message
                    }
                }
            }

            // Populate the ViewData with the UserId for the dropdown list in the view
            ViewData["UserId"] = new SelectList(_clients, "Id", "Id", article.UserId);

            return View(article); // Return the view with the invalid model
        }


        // GET: Articles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles.FindAsync(id);
            if (article == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_clients, "Id", "Id", article.UserId);
            return View(article);
        }

        // POST: Articles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Reference,DateAchat,DureeGarantie,UserId")] Article article)
        {
            if (id != article.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(article);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArticleExists(article.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", article.UserId);
            return View(article);
        }

        // GET: Articles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var article = await _context.Articles
                .Include(a => a.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (article == null)
            {
                return NotFound();
            }

            return View(article);
        }

        // POST: Articles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _context.Articles.FindAsync(id);
            if (article != null)
            {
                _context.Articles.Remove(article);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArticleExists(int id)
        {
            return _context.Articles.Any(e => e.Id == id);
        }
    }
}

ServiceApresVenteApp/Controllers/ReclamationsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceApresVente.Models;
using ServiceApresVenteApp.Repositories;

namespace ServiceApresVenteApp.Controllers
{
    public class ReclamationsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IUserRepository userRepository;
        private readonly IArticleRepository articleRepository;


        public ReclamationsController(ApplicationDbContext context, IUserRepository userRepository, IArticleRepository articleRepository)
        {
            _context = context;
            this.userRepository = userRepository;
            this.articleRepository = articleRepository;
        }

        // GET: Reclamations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reclamations.Include(r => r.Article).ToListAsync());
        }

        // GET: Reclamations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reclamation = await _context.Reclamations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reclamation == null)
            {
                return NotFound();
            }

            return View(reclamation);
        }

        // GET: Reclamations/Create
        public IActionResult Create()
        {
            ViewData["ArticleId"] = new SelectList(_context.Articles.ToList(), "Id", "Reference");
            

            return View();
        }
        public IActionResult GetArticleName(int id)
        {
            var article = articleRepository.GetById(id);
            if (article != null)
            {
                return Json(article.Nom); // Assuming the property for the name is 'Nom'
            }
            return Json("Article not found");
        }


        // POST: Reclamations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Description,DateReclamation,ArticleId")] Reclamation reclamation)
        {
            if (ModelState.IsValid)
            {
                reclamation.Statut = StatutReclamation.EnAttente;
                _context.Add(reclamation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reclamation);
        }
        public IActionResult CreateWithArticleId(int ArticleId)
        {
            ViewData["ArticleId"] = ArticleId;
            ViewData["Nom"] = articleRepository.GetById(ArticleId).Nom;
            ViewData["Reference"] = articleRepository.GetById(ArticleId).Reference;
            
            
           
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWithArticleId([Bind("Description,DateReclamation,ArticleId")] Reclamation reclamation)
        {
            if (ModelState.IsValid)
            {
                reclamation.Statut = StatutReclamation.EnAttente;
                _context.Add(reclamation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reclamation);
        }

        // GET: Reclamations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewData["ArticleId"] = new SelectList(_context.Articles.ToList(), "Id", "Reference");

            var reclamation = await _context.Reclamations.FindAsync(id);
            if (reclamation == null)
            {
                return NotFound();
            }
            return View(reclamation);
        }

        // POST: Reclamations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,DateReclamation,ArticleId")] Reclamation reclamation)
        {
            if (id != reclamation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reclamation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReclamationExists(reclamation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reclamation);
        }

        // GET: Reclamations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reclamation = await _context.Reclamations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reclamation == null)
            {
                return NotFound();
            }

            return View(reclamation);
        }

        // POST: Reclamations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reclamation = await _context.Reclamations.FindAsync(id);
            if (reclamation != null)
            {
                _context.Reclamations.Remove(reclamation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReclamationExists(int id)
        {
            return _context.Reclamations.Any(e => e.Id == id);
        }
        [Authorize(Roles ="Responsable")]
        // GET: 
        public async Task<IActionResult> EditForResponsable(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.StatusReclamation = StatutReclamation.EnCours;
            var reclamation = await _context.Reclamations.FindAsync(id);
            if (reclamation == null)
            {
                return NotFound();
            }
            return View(reclamation);
        }

        // POST: Reclamations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Responsable")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditForResponsable(int id, [Bind("Id,Description,Statut,DateReclamation,ArticleId")] Reclamation reclamation)
        {
            var existingTask = _context.Reclamations.Find(id);
            if (id != reclamation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    existingTask.Statut = StatutReclamation.EnCours;
                    var article = _context.Articles.Find(existingTask.ArticleId);
                    
                    var intervention = new Intervention
                    {
                        ReclamationId = reclamation.Id,
                        EstSousGarantie =
                        reclamation.DateReclamation <=
                        article.DateAchat.AddYears(article.DureeGarantie)
                    };

                    _context.Update(existingTask);
                    _context.Add(intervention);
                    await _context.SaveChangesAsync();
                    
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReclamationExists(reclamation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(reclamation);
        }

        public async Task<IActionResult> GetInterventionByReclamationId(int id)
        {
            var intervensionId = _context.Reclamations.Include(r=> r.Intervention).FirstOrDefault(i => i.Id==id).Intervention.Id;
            return RedirectToAction("Edit", "Interventions", new {id = intervensionId});
        }
    }
}

ServiceApresVenteApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ServiceApresVente.Models
@using System.Security.Claims
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Service Après Vente</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UserWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Account" asp-action="Login">Service Après Vente</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav ml-auto">

                        @*If the user is signed-in display Logout link*@
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Client"))
                        {
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="Client" asp-action="Index">

                                    Articles
                                </a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="Reclamations" asp-action="Index">

                                    Reclamations
                                </a>
                            </li>
                        }
                        
                       
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Responsable"))
                        {
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="Articles" asp-action="Index">

                                    Articles
                                </a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="Reclamations" asp-action="Index">

                                    Reclamations
                                </a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="Interventions" asp-action="Index">

                                    Interventions
                                </a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="PieceDeRechanges" asp-action="Index">

                                    Pieces de Rechange
                                </a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">

                                <form method="post" asp-controller="account" asp-action="logout">
                                    <button type="submit" style="width:auto"
                                            class="nav-link btn btn-link py-0">

                                        Logout @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="Account" asp-action="Register">

                                    Register
                                </a>
                            </li>
                            <li class="nav-item">

                                <a class="nav-link" asp-controller="Account" asp-action="Login">

                                    Login
                                </a>
                            </li>
                        }
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - UserWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/CustomScript.js"></script>
    <script src="~/js/reclamation.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>